import {
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Cake,
  Camera,
  Car,
  Coffee,
  Coins,
  CreditCard,
  Droplets,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  House,
  Lamp,
  Leaf,
  Music,
  Package,
  Palette,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Star,
  Tag,
  Ticket,
  TrainFront,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Lijniconen voor potjes (lucide-react). In de database staat alleen de sleutel;
 * de sleutels zijn stabiel, de iconen kunnen later gewisseld worden.
 */
export const CATEGORY_ICONS = {
  "shopping-cart": ShoppingCart,
  "shopping-basket": ShoppingBasket,
  utensils: Utensils,
  coffee: Coffee,
  beer: Beer,
  pizza: Pizza,
  cake: Cake,
  train: TrainFront,
  bus: Bus,
  bike: Bike,
  car: Car,
  fuel: Fuel,
  plane: Plane,
  house: House,
  lamp: Lamp,
  zap: Zap,
  droplets: Droplets,
  wifi: Wifi,
  repeat: Repeat,
  smartphone: Smartphone,
  tv: Tv,
  film: Film,
  music: Music,
  gamepad: Gamepad2,
  shirt: Shirt,
  scissors: Scissors,
  "shopping-bag": ShoppingBag,
  "party-popper": PartyPopper,
  ticket: Ticket,
  gift: Gift,
  "piggy-bank": PiggyBank,
  banknote: Banknote,
  coins: Coins,
  wallet: Wallet,
  "hand-coins": HandCoins,
  "credit-card": CreditCard,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  dumbbell: Dumbbell,
  "heart-pulse": HeartPulse,
  pill: Pill,
  "paw-print": PawPrint,
  baby: Baby,
  leaf: Leaf,
  palette: Palette,
  camera: Camera,
  wrench: Wrench,
  umbrella: Umbrella,
  receipt: Receipt,
  package: Package,
  heart: Heart,
  star: Star,
  globe: Globe,
  tag: Tag,
} satisfies Record<string, LucideIcon>;

export type CategoryIconKey = keyof typeof CATEGORY_ICONS;

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS) as CategoryIconKey[];

export const DEFAULT_CATEGORY_ICON: CategoryIconKey = "tag";

export function isCategoryIcon(value: unknown): value is CategoryIconKey {
  return typeof value === "string" && value in CATEGORY_ICONS;
}

/** Nederlandse namen voor toegankelijkheid en zoeken. */
export const CATEGORY_ICON_LABELS: Record<CategoryIconKey, string> = {
  "shopping-cart": "Winkelwagen",
  "shopping-basket": "Mandje",
  utensils: "Bestek",
  coffee: "Koffie",
  beer: "Bier",
  pizza: "Pizza",
  cake: "Taart",
  train: "Trein",
  bus: "Bus",
  bike: "Fiets",
  car: "Auto",
  fuel: "Tanken",
  plane: "Vliegtuig",
  house: "Huis",
  lamp: "Lamp",
  zap: "Energie",
  droplets: "Water",
  wifi: "Internet",
  repeat: "Herhaling",
  smartphone: "Telefoon",
  tv: "Televisie",
  film: "Film",
  music: "Muziek",
  gamepad: "Gamen",
  shirt: "Kleding",
  scissors: "Kapper",
  "shopping-bag": "Winkelen",
  "party-popper": "Feest",
  ticket: "Ticket",
  gift: "Cadeau",
  "piggy-bank": "Spaarvarken",
  banknote: "Bankbiljet",
  coins: "Munten",
  wallet: "Portemonnee",
  "hand-coins": "Geld geven",
  "credit-card": "Betaalpas",
  briefcase: "Werk",
  "graduation-cap": "Studie",
  "book-open": "Boeken",
  dumbbell: "Sport",
  "heart-pulse": "Zorg",
  pill: "Medicijnen",
  "paw-print": "Huisdier",
  baby: "Kind",
  leaf: "Natuur",
  palette: "Creatief",
  camera: "Foto",
  wrench: "Klussen",
  umbrella: "Verzekering",
  receipt: "Bonnetje",
  package: "Pakket",
  heart: "Hart",
  star: "Ster",
  globe: "Wereld",
  tag: "Label",
};
